# Generated by Django 4.2.3 on 2023-08-19 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingbids', to='auctions.listings', verbose_name='listing'),
        ),
        migrations.AddField(
            model_name='bids',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='comments',
            name='listing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingcomments', to='auctions.listings', verbose_name='listing'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='listings',
            name='bids',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='bidsonlisting', to='auctions.bids', verbose_name='bids'),
        ),
        migrations.AddField(
            model_name='listings',
            name='comments',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentsonlisting', to='auctions.comments', verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='listings',
            name='item_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='listings',
            name='item_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listings',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
