# Generated by Django 4.2.3 on 2023-08-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_amount_bids_listing_bids_user_comments_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='item_price',
            new_name='starting_bid',
        ),
        migrations.RenameField(
            model_name='listings',
            old_name='item_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='listings',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='listings',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='listings',
            name='image_link',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
