# Generated by Django 4.2.3 on 2023-08-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_item_price_listings_starting_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('F', 'Fasion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home'), ('HW', 'Hardware')], default='', max_length=200),
        ),
    ]
