# Generated by Django 4.2.3 on 2023-08-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listings_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='active_state',
            field=models.BooleanField(default=False),
        ),
    ]
