# Generated by Django 4.2.3 on 2023-08-20 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_listings_active_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bids',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidsonlisting', to='auctions.bids', verbose_name='bids'),
        ),
        migrations.AlterField(
            model_name='listings',
            name='comments',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentsonlisting', to='auctions.comments', verbose_name='comments'),
        ),
    ]
