# Generated by Django 4.2.3 on 2023-08-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_listings_bids_alter_listings_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='bids',
        ),
        migrations.RemoveField(
            model_name='listings',
            name='comments',
        ),
    ]
