# Generated by Django 4.2.3 on 2023-08-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listings_bids_remove_listings_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image_link',
            field=models.URLField(default='', max_length=1000),
        ),
    ]
