# Generated by Django 4.2.3 on 2023-08-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_status',
            field=models.BooleanField(default=False),
        ),
    ]
