# Generated by Django 4.2.3 on 2023-08-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_watchlist_watchlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='starting_bid',
            new_name='price',
        ),
    ]
