# Generated by Django 4.2.3 on 2023-08-22 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_listings_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(choices=[('F', 'Fasion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home'), ('HW', 'Hardware')], default='', max_length=200),
        ),
    ]
